// /** Declaration file generated by dts-gen */


//     class evmasm {
//         constructor(...args)

//         add(...args)

//         addmod(...args)

//         address(...args)

//         and(...args)

//         balance(...args)

//         blockhash(...args)

//         byte(...args)

//         call(...args)

//         callcode(...args)

//         calldatacopy(...args)

//         calldataload(...args)

//         calldatasize(...args)

//         caller(...args)

//         callvalue(...args)

//         codecopy(...args)

//         codesize(...args)

//         coinbase(...args)

//         create(...args)

//         createTxData(...args)

//         delegatecall(...args)

//         difficulty(...args)

//         div(...args)

//         dup(...args)

//         eq(...args)

//         exp(...args)

//         extcodecopy(...args)

//         extcodesize(...args)

//         gas(...args)

//         gaslimit(...args)

//         gasprice(...args)

//         gt(...args)

//         invalid(...args)

//         iszero(...args)

//         jmp(...args)

//         jmpi(...args)

//         keccak(...args)

//         label(...args)

//         log0(...args)

//         log1(...args)

//         log2(...args)

//         log3(...args)

//         log4(...args)

//         lt(...args)

//         mload(...args)

//         mod(...args)

//         msize(...args)

//         mstore(...args)

//         mstore8(...args)

//         mul(...args)

//         mulmod(...args)

//         not(...args)

//         number(...args)

//         or(...args)

//         origin(...args)

//         pc(...args)

//         pop(...args)

//         push(...args)

//         return(...args)

//         returndatacopy(...args)

//         returndatasize(...args)

//         revert(...args)

//         sdiv(...args)

//         selfdestruct(...args)

//         sgt(...args)

//         sha3(...args)

//         shor(...args)

//         signextend(...args)

//         sload(...args)

//         slt(...args)

//         smod(...args)

//         sstore(...args)

//         staticcall(...args)

//         stop(...args)

//         sub(...args)

//         swap(...args)

//         timestamp(...args)
//     }

//     //next
//     class smt_memdb {
//         constructor(...args)

//         get(...args)

//         getRoot(...args)

//         multiDel(...args)

//         multiGet(...args)

//         multiIns(...args)

//         setRoot(...args)
//     }

//     //next
//     function poseidon(inputs)

//     //next
//     function poseidon_slow(inputs)

//     //next
//     namespace babyjub {
//         const A

//         const Base8

//         const D

//         const Generator

//         const order

//         const p

//         const subOrder

//         function addPoint(a, b)

//         function inCurve(P)

//         function inSubgroup(P)

//         function mulPointEscalar(base, e)

//         function packPoint(P)

//         function unpackPoint(_buff)

//         namespace F {
//             const R

//             const Ri

//             const bitLength

//             const half

//             const m

//             const mask

//             const n32

//             const n64

//             const n8

//             const negone

//             const nqr

//             const nqr_to_t

//             const one

//             const p

//             const s

//             const sqrt_q

//             const sqrt_s

//             const sqrt_t

//             const sqrt_tm1d2

//             const sqrt_z

//             const t

//             const two

//             const type

//             const zero

//             function add(...args)

//             function band(...args)

//             function bnot(...args)

//             function bor(...args)

//             function bxor(...args)

//             function div(...args)

//             function e(...args)

//             function eq(...args)

//             function exp(...args)

//             function fromRng(...args)

//             function fromRprBE(...args)

//             function fromRprBEM(...args)

//             function fromRprLE(...args)

//             function fromRprLEM(...args)

//             function geq(...args)

//             function gt(...args)

//             function idiv(...args)

//             function inv(...args)

//             function isZero(...args)

//             function land(...args)

//             function leq(...args)

//             function lnot(...args)

//             function lor(...args)

//             function lt(...args)

//             function mod(...args)

//             function mul(...args)

//             function mulScalar(...args)

//             function neg(...args)

//             function neq(...args)

//             function normalize(...args)

//             function pow(...args)

//             function random(...args)

//             function shl(...args)

//             function shr(...args)

//             function sqrt(a)

//             function sqrt_old(...args)

//             function square(...args)

//             function sub(...args)

//             function toRprBE(...args)

//             function toRprBEM(...args)

//             function toRprLE(...args)

//             function toRprLEM(...args)

//             function toString(...args)
//         }
//     }

//     //next
//      namespace eddsa {
//         function packSignature(sig)

//         function pruneBuffer(_buff)

//         function prv2pub(prv)

//         function sign(prv, msg)

//         function signMiMC(prv, msg)

//         function signMiMCSponge(prv, msg)

//         function signPoseidon(prv, msg)

//         function unpackSignature(sigBuff)

//         function verify(msg, sig, A)

//         function verifyMiMC(msg, sig, A)

//         function verifyMiMCSponge(msg, sig, A)

//         function verifyPoseidon(msg, sig, A)
//     }


//     //next
//      namespace mimc7 {
//         function getConstants(seed, nRounds)

//         function getIV(seed)

//         function hash(_x_in, _k)

//         function multiHash(arr, key)

//         namespace F {
//             const R

//             const Ri

//             const bitLength

//             const half

//             const m

//             const mask

//             const n32

//             const n64

//             const n8

//             const negone

//             const nqr

//             const nqr_to_t

//             const one

//             const p

//             const s

//             const sqrt_q

//             const sqrt_s

//             const sqrt_t

//             const sqrt_tm1d2

//             const sqrt_z

//             const t

//             const two

//             const type

//             const zero

//             function add(...args)

//             function band(...args)

//             function bnot(...args)

//             function bor(...args)

//             function bxor(...args)

//             function div(...args)

//             function e(...args)

//             function eq(...args)

//             function exp(...args)

//             function fromRng(...args)

//             function fromRprBE(...args)

//             function fromRprBEM(...args)

//             function fromRprLE(...args)

//             function fromRprLEM(...args)

//             function geq(...args)

//             function gt(...args)

//             function idiv(...args)

//             function inv(...args)

//             function isZero(...args)

//             function land(...args)

//             function leq(...args)

//             function lnot(...args)

//             function lor(...args)

//             function lt(...args)

//             function mod(...args)

//             function mul(...args)

//             function mulScalar(...args)

//             function neg(...args)

//             function neq(...args)

//             function normalize(...args)

//             function pow(...args)

//             function random(...args)

//             function shl(...args)

//             function shr(...args)

//             function sqrt(a)

//             function sqrt_old(...args)

//             function square(...args)

//             function sub(...args)

//             function toRprBE(...args)

//             function toRprBEM(...args)

//             function toRprLE(...args)

//             function toRprLEM(...args)

//             function toString(...args)
//         }
//     }


//     //next
//      namespace mimc_gencontract {
//         const abi: {
//             constant: boolean
//             inputs: {
//                 name
//                 type
//             }[]
//             name
//             outputs: {
//                 name
//                 type
//             }[]
//             payable: boolean
//             stateMutability
//             type
//         }[]

//         function createCode(seed, n)
//     }


//     //next
//      namespace mimcsponge {
//         function getConstants(seed, nRounds)

//         function getIV(seed)

//         function hash(_xL_in, _xR_in, _k)

//         function multiHash(arr, key, numOutputs)
//     }


//     //next
//      namespace mimcsponge_gencontract {
//         const abi: {
//             constant: boolean
//             inputs: {
//                 name
//                 type
//             }[]
//             name
//             outputs: {
//                 name
//                 type
//             }[]
//             payable: boolean
//             stateMutability
//             type
//         }[]

//         function createCode(seed, n)
//     }


//     //next
//      namespace pedersenHash {
//         function getBasePoint(baseHashType, pointIdx)

//         function hash(msg, options)
//     }


//     //next
//      namespace poseidon_gencontract {
//         function createCode(nInputs)

//         function generateABI(nInputs)
//     }

//     //next
//      namespace smt {
//         class SMT {
//             constructor(...args)

//             delete(...args)

//             find(...args)

//             insert(...args)

//             update(...args)
//         }

//         class SMTMemDB {
//             constructor(...args)

//             get(...args)

//             getRoot(...args)

//             multiDel(...args)

//             multiGet(...args)

//             multiIns(...args)

//             setRoot(...args)
//         }

//         function loadFromFile(fileName)

//         function newMemEmptyTrie()
//     }


//     //next
//      namespace smt_hashes_mimc {
//         function hash0(left, right)

//         function hash1(key, value)

//         namespace F {
//             const R

//             const Ri

//             const bitLength

//             const half

//             const m

//             const mask

//             const n32

//             const n64

//             const n8

//             const negone

//             const nqr

//             const nqr_to_t

//             const one

//             const p

//             const s

//             const sqrt_q

//             const sqrt_s

//             const sqrt_t

//             const sqrt_tm1d2

//             const sqrt_z

//             const t

//             const two

//             const type

//             const zero

//             function add(...args)

//             function band(...args)

//             function bnot(...args)

//             function bor(...args)

//             function bxor(...args)

//             function div(...args)

//             function e(...args)

//             function eq(...args)

//             function exp(...args)

//             function fromRng(...args)

//             function fromRprBE(...args)

//             function fromRprBEM(...args)

//             function fromRprLE(...args)

//             function fromRprLEM(...args)

//             function geq(...args)

//             function gt(...args)

//             function idiv(...args)

//             function inv(...args)

//             function isZero(...args)

//             function land(...args)

//             function leq(...args)

//             function lnot(...args)

//             function lor(...args)

//             function lt(...args)

//             function mod(...args)

//             function mul(...args)

//             function mulScalar(...args)

//             function neg(...args)

//             function neq(...args)

//             function normalize(...args)

//             function pow(...args)

//             function random(...args)

//             function shl(...args)

//             function shr(...args)

//             function sqrt(a)

//             function sqrt_old(...args)

//             function square(...args)

//             function sub(...args)

//             function toRprBE(...args)

//             function toRprBEM(...args)

//             function toRprLE(...args)

//             function toRprLEM(...args)

//             function toString(...args)
//         }
//     }


//     //next
//      namespace smt_hashes_poseidon {
//         function hash0(left, right)

//         function hash1(key, value)

//         namespace F {
//             const R

//             const Ri

//             const bitLength

//             const half

//             const m

//             const mask

//             const n32

//             const n64

//             const n8

//             const negone

//             const nqr

//             const nqr_to_t

//             const one

//             const p

//             const s

//             const sqrt_q

//             const sqrt_s

//             const sqrt_t

//             const sqrt_tm1d2

//             const sqrt_z

//             const t

//             const two

//             const type

//             const zero

//             function add(...args)

//             function band(...args)

//             function bnot(...args)

//             function bor(...args)

//             function bxor(...args)

//             function div(...args)

//             function e(...args)

//             function eq(...args)

//             function exp(...args)

//             function fromRng(...args)

//             function fromRprBE(...args)

//             function fromRprBEM(...args)

//             function fromRprLE(...args)

//             function fromRprLEM(...args)

//             function geq(...args)

//             function gt(...args)

//             function idiv(...args)

//             function inv(...args)

//             function isZero(...args)

//             function land(...args)

//             function leq(...args)

//             function lnot(...args)

//             function lor(...args)

//             function lt(...args)

//             function mod(...args)

//             function mul(...args)

//             function mulScalar(...args)

//             function neg(...args)

//             function neq(...args)

//             function normalize(...args)

//             function pow(...args)

//             function random(...args)

//             function shl(...args)

//             function shr(...args)

//             function sqrt(a)

//             function sqrt_old(...args)

//             function square(...args)

//             function sub(...args)

//             function toRprBE(...args)

//             function toRprBEM(...args)

//             function toRprLE(...args)

//             function toRprLEM(...args)

//             function toString(...args)
//         }
//     }

