# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DAOCODERS CI

on:
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '14.x'
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'
      - run: npm install
      - run: npm ci
      - run: npm run test:org
        env:
          MONGODB_TEST_URL: 'mongodb://localhost:27017/testing_daocoders'
